using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NotesDataAccess.Models
{
    public class NoteModel
    {
        /// <summary>
        /// Unique Identifyer for the note.
        /// Will be autogenerated or used to Identify a not for updates or deletion
        /// </summary>
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        /// <summary>
        /// Owner of the note
        /// </summary>
        // TODO: change Owner to a own type and also store it in a table
        // Should be used later for acess controll and also be autogenerated
        public string Owner { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
    }
}
